baseURL = "http://example.org/"
languageCode = "en-us"
title = "belitzki. Press Kit"
publishDir = "docs"
theme = "hyde"
[Menus]
  main = [
      {Name = "Facebook", URL = "https://facebook.com/belitzki/"},
      {Name = "Bandcamp", URL = "https://www.linkedin.com/in/username/"},
      {Name = "Spotify", URL = "https://www.linkedin.com/in/username/"},
      {Name = "📧 belitzki@web.de"},
      {Name = "📱 0157 39334823 (Krätze)"}
  ]
[params]
  description = "Indiepunkpoprockgedöns"