baseURL = "http://paulklemm.com/belitzki-presskit"
languageCode = "en-us"
title = "belitzki. Press Kit"
publishDir = "docs"
theme = "hyde"
[Menus]
  main = [
      {Name = "Facebook", URL = "https://www.facebook.com/belitzki/"},
      {Name = "Bandcamp", URL = "https://belitzki.bandcamp.com/"},
      {Name = "Spotify", URL = "https://open.spotify.com/artist/4r0BGqRyBH9BFJHUYHlBFZ?si=z99fXAvaQ_a1VwWD8-YdJw"},
      {Name = "📧 belitzki@web.de"},
      {Name = "📱 0157 39334823 (Krätze)"}
  ]
[params]
  description = "Indiepunkpoprockgedöns"